<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>BASE_OPEN_GL</RootNamespace>
    <AssemblyName>BASE_OPEN_GL</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>BASE_OPEN_GL</AssemblyTitle>
    <Product>BASE_OPEN_GL</Product>
    <Copyright>Copyright ©  2020</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <PlatformTarget>x86</PlatformTarget>
	  <Nullable>disable</Nullable>
	  <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="DevIL.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="freeglut.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="ILU.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="ILUT.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Info_Texture.txt" />
    <Content Include="logo.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="oeil.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="OpenGLDotNet.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MemoryPack" Version="1.21.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="OpenGLDotNet">
      <HintPath>..\..\BASE_OPEN_GL_2022_V1_4\BASE_OPEN_GL_2022_V1_4\BASE_OPEN_GL_2022_V1_4\BASE_OPEN_GL_2022\BASE_OPEN_GL_2022\OpenGLDotNet.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>